#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := gatt_cpp_payments
#CFLAGS += -D LOG_LOCAL_LEVEL=ESP_LOG_DEBUG

COMPONENT_ADD_INCLUDEDIRS := components/include

include $(IDF_PATH)/make/project.mk
