#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := BLE_cpp_payments

COMPONENT_ADD_INCLUDEDIRS := components/include main/crypto-lib

include $(IDF_PATH)/make/project.mk
